# Generated by Django 5.0.4 on 2024-04-06 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_category_contact_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='nome',
        ),
    ]
