# Generated by Django 5.0.4 on 2024-04-06 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
